### ISSUE TITLE
Update home page

### ISSUE THREAD

**Issue by ivanvinski** [ivanvinski/ivanvinski.com#50]
## Tasks

* [x] Change Gender to Age
* [x] Change Current workplace to Experience
* [x] Change Available for hire value to Maybe
* [x] Change texts of existing popovers
* [x] Add popover to Occupation value
* [x] Add top padding above image on smaller screens

### Desktop

![mockup-001-home](https://user-images.githubusercontent.com/14854181/98078690-d2ff8c00-1e72-11eb-894d-ae5f3004f4d2.png)

### Mobile

![mockup-001-home_mobile](https://user-images.githubusercontent.com/14854181/98078959-5b7e2c80-1e73-11eb-9e2d-a1488e030652.png)
