### ISSUE TITLE
Update portfolio page

### ISSUE THREAD

**Issue by ivanvinski** [ivanvinski/ivanvinski.com#51]
## Tasks

* [x] Remove Devzact from projects list
* [x] Put ivanvinski.com project first
* [x] Add GitHub repositories link as the last item

### Desktop

![mockup-002-portfolio](https://user-images.githubusercontent.com/14854181/98080794-49ea5400-1e76-11eb-92c3-99aa34f4cc50.png)

### Mobile

![mockup-002-portfolio_mobile](https://user-images.githubusercontent.com/14854181/98080803-4d7ddb00-1e76-11eb-9043-fee0334fa4ad.png)
